const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Mouse,
		C3.Behaviors.custom,
		C3.Behaviors.solid,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Arr,
		C3.Plugins.Function,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Behaviors.Pin,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Button.Acts.SetPos,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.lunarray_LiteTween.Acts.Reverse,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsClose,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Behaviors.lunarray_LiteTween.Acts.SetDuration,
		C3.Behaviors.lunarray_LiteTween.Acts.SetEasing,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Function.Exps.Param,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.StopAll
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{Audio: 0},
	{LiteTween: 0},
	{play: 0},
	{Mouse: 0},
	{matched: 0},
	{column: 0},
	{row: 0},
	{type: 0},
	{CustomMovement: 0},
	{Solid: 0},
	{DragDrop: 0},
	{block: 0},
	{match: 0},
	{Function: 0},
	{Sprite2: 0},
	{SpriteFont: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Синусоида: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Timer: 0},
	{Sprite8: 0},
	{SpriteFont2: 0},
	{Particles: 0},
	{Fade: 0},
	{Sprite9: 0},
	{LiteTween2: 0},
	{ring02_: 0},
	{flare02_blue: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite: 0},
	{Pin: 0},
	{Sprite10: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{SpriteFont3: 0},
	{Sprite17: 0},
	{BestScoreFont: 0},
	{best: 0},
	{Dictionary: 0},
	{ЛокальноеХранилище: 0},
	{Прикрепить: 0},
	{image: 0},
	{GameScore: 0},
	{Синусоид: 0},
	{distancesguisheet: 0},
	{вид: 0},
	{бан: 0},
	{image2: 0},
	{image3: 0},
	{image4: 0},
	{image5: 0},
	{ButtonSound: 0},
	{sdafsd: 0},
	{ВАЫП: 0},
	{старт: 0},
	{Sprite18: 0},
	{Запуск: 0},
	{баннер: 0},
	{test: 0},
	{score: 0},
	{gamestart: 0},
	{SPAWNX: 0},
	{SPAWNY: 0},
	{Loopx: 0},
	{Loopy: 0},
	{pick: 0},
	{touchx: 0},
	{touchx2: 0},
	{touchy: 0},
	{touchy2: 0},
	{destoryx: 0},
	{destoryy: 0},
	{blocktype: 0},
	{downY: 0},
	{checkfin: 0},
	{selblockrow: 0},
	{selblockcolumn: 0},
	{BestScore: 0},
	{up: 0},
	{self: 0},
	{down: 0},
	{r_block: 0},
	{l_block: 0},
	{self2: 0},
	{pickcount: 0},
	{highest: 0},
	{lowest: 0},
	{nowrow: 0},
	{matchcount: 0},
	{loopyy: 0},
	{blockx: 0},
	{blocky: 0},
	{movetype: 0},
	{SoundOn: 0},
	{Sound: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	play: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	block: class extends self.ISpriteInstance {},
	match: class extends self.IArrayInstance {},
	Function: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	ring02_: class extends self.ISpriteInstance {},
	flare02_blue: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	image: class extends self.ISpriteInstance {},
	GameScore: class extends self.IInstance {},
	distancesguisheet: class extends self.ISpriteInstance {},
	вид: class extends self.IButtonInstance {},
	бан: class extends self.IButtonInstance {},
	image2: class extends self.ISpriteInstance {},
	image3: class extends self.ISpriteInstance {},
	image4: class extends self.ISpriteInstance {},
	image5: class extends self.ISpriteInstance {},
	ButtonSound: class extends self.ISpriteInstance {},
	sdafsd: class extends self.ISpriteInstance {},
	ВАЫП: class extends self.ISpriteInstance {},
	старт: class extends self.IButtonInstance {},
	Sprite18: class extends self.ISpriteInstance {}
}