const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Behaviors.custom,
		C3.Plugins.Function,
		C3.Plugins.Arr,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.TextBox,
		C3.Behaviors.Flash,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.custom.Acts.AccelerateAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.custom.Acts.Reverse,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.custom.Acts.Stop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Cnds.OnClicked,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.ScriptsInEvents.Loadingsettings_Event2_Act8
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Cannon: 0},
	{CannonBase: 0},
	{Touch: 0},
	{used: 0},
	{CustomMovement: 0},
	{Ball: 0},
	{Borders: 0},
	{group: 0},
	{CurX: 0},
	{CurY: 0},
	{BallCollision: 0},
	{Function: 0},
	{CurrentGame: 0},
	{Tiles: 0},
	{Dist: 0},
	{Groups: 0},
	{Array: 0},
	{TopBorder: 0},
	{ConnectDeleter: 0},
	{BtnRestart: 0},
	{ScoreFont: 0},
	{LocalStorage: 0},
	{BtnPlay: 0},
	{Frame: 0},
	{Browser: 0},
	{BtnBack: 0},
	{HighScoreFont: 0},
	{Audio: 0},
	{Sound: 0},
	{BtnSound: 0},
	{BallsFont: 0},
	{FrameTop: 0},
	{Sine: 0},
	{Frames: 0},
	{Professor: 0},
	{LevelsFont: 0},
	{FrameDown: 0},
	{TimeFont: 0},
	{LoadingBar: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{Синусоид: 0},
	{lidear: 0},
	{GamePush: 0},
	{texttaptoplaysheet: 0},
	{ballcolor: 0},
	{pngwingcom: 0},
	{image: 0},
	{Login: 0},
	{Мигание: 0},
	{ок: 0},
	{image2: 0},
	{image3: 0},
	{image4: 0},
	{Background2: 0},
	{Minutes: 0},
	{Seconds: 0},
	{Shots: 0},
	{AdShow: 0},
	{ScoreBonus: 0},
	{HighScore: 0},
	{Clear: 0},
	{IsGameOver: 0},
	{Score: 0},
	{MoveEnded: 0},
	{DestrGroup: 0},
	{LineAdded: 0},
	{ShootCounter: 0},
	{TileY: 0},
	{TileX: 0},
	{InShoot: 0},
	{login: 0},
	{name: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Cannon: class extends self.ISpriteInstance {},
	CannonBase: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Ball: class extends self.ISpriteInstance {},
	Borders: class extends self.ISpriteInstance {},
	BallCollision: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	CurrentGame: class extends self.IArrayInstance {},
	Tiles: class extends self.ISpriteInstance {},
	Dist: class extends self.IArrayInstance {},
	Groups: class extends self.IArrayInstance {},
	Array: class extends self.IArrayInstance {},
	TopBorder: class extends self.ISpriteInstance {},
	ConnectDeleter: class extends self.IArrayInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BallsFont: class extends self.ISpriteFontInstance {},
	FrameTop: class extends self.ISpriteInstance {},
	Frames: class extends self.ISpriteInstance {},
	Professor: class extends self.ISpriteInstance {},
	LevelsFont: class extends self.ISpriteFontInstance {},
	FrameDown: class extends self.ISpriteInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	lidear: class extends self.ISpriteInstance {},
	GamePush: class extends self.IInstance {},
	texttaptoplaysheet: class extends self.ISpriteInstance {},
	ballcolor: class extends self.ISpriteInstance {},
	pngwingcom: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	Login: class extends self.ITextInputInstance {},
	ок: class extends self.ISpriteInstance {},
	image2: class extends self.ISpriteInstance {},
	image3: class extends self.ISpriteInstance {},
	image4: class extends self.ISpriteInstance {},
	Background2: class extends self.ISpriteInstance {}
}